language: node_js
node_js:
- '0.11'
before_install: 
install:
- npm install
before_script:
- npm link .
script:
- ./ci/build.js
- ./ci/test.js
- ./ci/cover.js
- ./ci/report.js
env:
  global:
  - secure: hEDZBnKJLBJlYZ03g9/GE36cvPm4oSkHnZyMAZ8pkocdp0+iZoaGvvRkfyEQOfz89Yx7q5kuZA91HFckfJmNYlzso7d391UjAKglCRH3W5DbPAcsXMrOAwi/zY9n1zssf/jTwPK9tJiM5FdTOn+kUwQiZ+iAwQoBtWLy9amwvVV7PgdZVuNTfNqt1xWhM0RfbjFMYBKWKeMOONX/mfeHYF3Kf5L1C6irEa3u1Wl2GtBMBO/V64LZ7Gm7GKz9t8OKdy9RkMjIz5M7dvffp/cefSVj3CutcUI55E58W0xM2A1V20JYLMfQSmk8/g+59F+QPaEHXE51KNnjoOonNddvzTWrnmtu4q0ib/7DujyQzRQm9PVkbBUHPfCeZNPkF7R4M72C6ds+bJH0F/bd/SbtvSPgdHPMKE3wHD7RpTWPsSHjTC5ttIuRwqE13xB8K/5SYiVn4JUmDUvRJZpIXX0Hia5caVOgF+lFbvzTZeUBOwUGZ5RkFv9FxgqHhHA5rkzjHvxevcpjM75mZfJibIK1oOhJDSM2TJNXQopMfQLOBYpP7zY64S5G40ryjVA1kp6jkXmP0flRKSGgF/BffuignPqXTXVEqih9oBw/aT3Gh5Y8ynhS1LL5SaS1IG4AJ4fP1xR/AYxny8W3iOf6QYLvIOtUp3YLPwY8l2lE/FIFoAM=
