language: node_js
node_js:
- '0.11'
before_install: 
install:
- npm install
before_script:
- npm link .
script:
- npm run build
- npm run test
- npm run cover
- npm run report
env:
  global:
  - secure: EkSc1k6l87YMB/DqOntNek4mjmNtS5lGfu6I9R6XMp+g+U/RjJ/W+v1Cr9dlexmnSZ0S5L7tTtwoN0cWnWe2VBAvpz4NaPzhC+vRVRnmld59Y8Q2cWlHHbbpADuQWaVE+evqa6RCzyDqsZgvAEJNyY3uZu9a47bUE802mItwtXXEFfhODLnbFuFLM6la97JTUvMiL8acnthNlxUAVZa79xORc+ujLE9i+dWeycFwT4IV83tnqiXZ1rmm5FbEDbVjDuXO+mO38hQwjLJG4PdiLu88BZNW9nLwK4ziavDmL6gaiImrZ3yJ7HV5CiM8bZHmygaD23+TaDh1vzfwFtVwgTLnKrqm80KPi0UE/R3RJHqkDOrH1OU+ZR3RTTRBTKGG/ZdOK69R9a/m7y4uxnKcbbCoHGR1c/uRO15HPsweQlu+NXrF9WkNCOVSXcE2lIWnsP8qdI++YItSu0G/fN172G5RecanX5akkIY69NX0ilZvk3ATJrIfmTPh12ocM8L4bapEu/3zzQkA4OS1EAmyhHprckysle39RmDnZkCuKYq8ubN4nJdupjshyl6FceTlFkDDxO10bAjCqiE1GB6cS5ZOhZ/UzX3rsIJf/2FZUqpcu1uLj+RE0CrfBx944P6jFForR6n+IJJu9cN7iyx2gbKc1bdGRjpwNuX1iIKcQW8=
  - secure: hEDZBnKJLBJlYZ03g9/GE36cvPm4oSkHnZyMAZ8pkocdp0+iZoaGvvRkfyEQOfz89Yx7q5kuZA91HFckfJmNYlzso7d391UjAKglCRH3W5DbPAcsXMrOAwi/zY9n1zssf/jTwPK9tJiM5FdTOn+kUwQiZ+iAwQoBtWLy9amwvVV7PgdZVuNTfNqt1xWhM0RfbjFMYBKWKeMOONX/mfeHYF3Kf5L1C6irEa3u1Wl2GtBMBO/V64LZ7Gm7GKz9t8OKdy9RkMjIz5M7dvffp/cefSVj3CutcUI55E58W0xM2A1V20JYLMfQSmk8/g+59F+QPaEHXE51KNnjoOonNddvzTWrnmtu4q0ib/7DujyQzRQm9PVkbBUHPfCeZNPkF7R4M72C6ds+bJH0F/bd/SbtvSPgdHPMKE3wHD7RpTWPsSHjTC5ttIuRwqE13xB8K/5SYiVn4JUmDUvRJZpIXX0Hia5caVOgF+lFbvzTZeUBOwUGZ5RkFv9FxgqHhHA5rkzjHvxevcpjM75mZfJibIK1oOhJDSM2TJNXQopMfQLOBYpP7zY64S5G40ryjVA1kp6jkXmP0flRKSGgF/BffuignPqXTXVEqih9oBw/aT3Gh5Y8ynhS1LL5SaS1IG4AJ4fP1xR/AYxny8W3iOf6QYLvIOtUp3YLPwY8l2lE/FIFoAM=
